_decdig : '0'-'9' ;
!whitespace : ' ' | '\t' | '\n' | '\r' ;
!comment : '#'  {.} '\n' ;

int_literal : _decdig { _decdig };

Root
  : IntLiteral
  | IntLiteral "+" Root
  | IntLiteral "*" Root
;

IntLiteral : int_literal;
