_decdig : '0'-'9' ;
!whitespace : ' ' | '\t' | '\n' | '\r' ;
!comment : '#'  {.} '\n' ;

int_literal : _decdig { _decdig };
plus : '+';
times : '*';

Root
  : int_literal
  | int_literal plus Root
  | int_literal times Root
;
