_decdig : '0'-'9' ;
!whitespace : ' ' | '\t' | '\n' | '\r' ;
!comment : '#'  {.} '\n' ;

int_literal : _decdig { _decdig };
plus: '+';
times: '*';

Root
  : Sum
;

Sum
  : int_literal RestOfProduct RestOfSum
;

RestOfSum
  : plus int_literal RestOfProduct RestOfSum
  | empty
;

RestOfProduct
  : times int_literal RestOfProduct
  | empty
;
