_decdig : '0'-'9' ;
!whitespace : ' ' | '\t' | '\n' | '\r' ;
!comment : '#'  {.} '\n' ;

int_literal : _decdig { _decdig };
plus: '+';
times: '*';

Root
  : AddTerm
;

AddTerm
  : AddTerm plus MulTerm
  | MulTerm
;

MulTerm
  : MulTerm times int_literal
  | int_literal
;
