_decdig : '0'-'9' ;
!whitespace : ' ' | '\t' | '\n' | '\r' ;
!comment : '#'  {.} '\n' ;

int_literal : _decdig { _decdig };
plus: '+';
times: '*';

Root
  : Sum
;

Sum
  : Sum plus Product
  | Product
;

Product
  : Product times int_literal
  | int_literal
;
