/**
 * Generated by lexgen_code.js from lexgen JSON tables. Do not edit.
 */
import { newToken, newEOFToken, newErrorToken, Location } from "../../generators/js/runtime/index.js";

const START_STATE = 0;

const TRANSITIONS = {
  0: [
    [9, 9, 1],
    [10, 10, 2],
    [13, 13, 3],
    [32, 32, 4],
    [34, 34, 5],
    [44, 44, 6],
    [45, 45, 7],
    [48, 48, 8],
    [49, 57, 9],
    [58, 58, 10],
    [91, 91, 11],
    [93, 93, 12],
    [102, 102, 13],
    [110, 110, 14],
    [116, 116, 15],
    [123, 123, 16],
    [125, 125, 17]
  ],
  5: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  7: [
    [48, 48, 8],
    [49, 57, 9]
  ],
  8: [
    [46, 46, 23],
    [69, 69, 24],
    [101, 101, 25]
  ],
  9: [
    [46, 46, 23],
    [48, 57, 26],
    [69, 69, 24],
    [101, 101, 25]
  ],
  13: [
    [97, 97, 27]
  ],
  14: [
    [117, 117, 28]
  ],
  15: [
    [114, 114, 29]
  ],
  18: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  20: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  21: [
    [34, 34, 30],
    [47, 47, 31],
    [92, 92, 32],
    [98, 98, 33],
    [102, 102, 34],
    [110, 110, 35],
    [114, 114, 36],
    [116, 116, 37],
    [117, 117, 38]
  ],
  22: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  23: [
    [48, 57, 39]
  ],
  24: [
    [43, 43, 40],
    [45, 45, 41],
    [48, 57, 42]
  ],
  25: [
    [43, 43, 40],
    [45, 45, 41],
    [48, 57, 42]
  ],
  26: [
    [46, 46, 23],
    [48, 57, 26],
    [69, 69, 24],
    [101, 101, 25]
  ],
  27: [
    [108, 108, 43]
  ],
  28: [
    [108, 108, 44]
  ],
  29: [
    [117, 117, 45]
  ],
  30: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  31: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  32: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  33: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  34: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  35: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  36: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  37: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  38: [
    [48, 57, 46],
    [65, 70, 47],
    [97, 102, 48]
  ],
  39: [
    [48, 57, 49],
    [69, 69, 24],
    [101, 101, 25]
  ],
  40: [
    [48, 57, 42]
  ],
  41: [
    [48, 57, 42]
  ],
  42: [
    [48, 57, 50]
  ],
  43: [
    [115, 115, 51]
  ],
  44: [
    [108, 108, 52]
  ],
  45: [
    [101, 101, 53]
  ],
  46: [
    [48, 57, 54],
    [65, 70, 55],
    [97, 102, 56]
  ],
  47: [
    [48, 57, 54],
    [65, 70, 55],
    [97, 102, 56]
  ],
  48: [
    [48, 57, 54],
    [65, 70, 55],
    [97, 102, 56]
  ],
  49: [
    [48, 57, 49],
    [69, 69, 24],
    [101, 101, 25]
  ],
  50: [
    [48, 57, 50]
  ],
  51: [
    [101, 101, 57]
  ],
  54: [
    [48, 57, 58],
    [65, 70, 59],
    [97, 102, 60]
  ],
  55: [
    [48, 57, 58],
    [65, 70, 59],
    [97, 102, 60]
  ],
  56: [
    [48, 57, 58],
    [65, 70, 59],
    [97, 102, 60]
  ],
  58: [
    [48, 57, 61],
    [65, 70, 62],
    [97, 102, 63]
  ],
  59: [
    [48, 57, 61],
    [65, 70, 62],
    [97, 102, 63]
  ],
  60: [
    [48, 57, 61],
    [65, 70, 62],
    [97, 102, 63]
  ],
  61: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  62: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ],
  63: [
    [32, 33, 18],
    [34, 34, 19],
    [35, 91, 20],
    [92, 92, 21],
    [93, 65535, 22]
  ]
};

const ACTIONS = {
  1: "!whitespace",
  2: "!whitespace",
  3: "!whitespace",
  4: "!whitespace",
  6: "comma",
  8: "number",
  9: "number",
  10: "colon",
  11: "lbracket",
  12: "rbracket",
  16: "lcurly",
  17: "rcurly",
  19: "string",
  26: "number",
  39: "number",
  42: "number",
  49: "number",
  50: "number",
  52: "null",
  53: "true",
  57: "false"
};

function lookupTransition(state, r) {
  const ranges = TRANSITIONS[state];
  if (!ranges) return null;
  for (const [from, to, next] of ranges) {
    if (r < from) return null;
    if (r >= from && r <= to) return next;
  }
  return null;
}

export class pgpg_JSONLexer {
  constructor(inputText) {
    this._input = inputText;
    this._length = inputText.length;
    this._index = 0;
    this._line = 1;
    this._column = 1;
  }

  scan() {
    for (;;) {
      if (this._index >= this._length)
        return newEOFToken(new Location(this._line, this._column, this._index));

      const startLine = this._line;
      const startCol = this._column;
      const startIndex = this._index;
      let state = START_STATE;
      let lastAcceptState = null;
      let lastAcceptIndex = this._index;
      let lastAcceptLine = this._line;
      let lastAcceptCol = this._column;

      while (this._index < this._length) {
        const r = this._input.codePointAt(this._index);
        const nextState = lookupTransition(state, r);
        if (nextState == null) break;
        this._index += r > 0xffff ? 2 : 1;
        if (this._input[this._index - 1] === "\n") {
          this._line++;
          this._column = 1;
        } else this._column++;
        state = nextState;
        if (ACTIONS[state] !== undefined) {
          lastAcceptState = state;
          lastAcceptIndex = this._index;
          lastAcceptLine = this._line;
          lastAcceptCol = this._column;
        }
      }

      if (lastAcceptState == null) {
        const r = this._index < this._length ? this._input.codePointAt(this._index) : 0;
        return newErrorToken(
          `lexer: unrecognized input ${String.fromCodePoint(r)}`,
          new Location(this._line, this._column, this._index),
        );
      }

      const lexeme = this._input.slice(startIndex, lastAcceptIndex);
      this._index = lastAcceptIndex;
      this._line = lastAcceptLine;
      this._column = lastAcceptCol;
      const tokenType = ACTIONS[lastAcceptState];
      if (tokenType.startsWith("!")) continue;
      return newToken(lexeme, tokenType, new Location(startLine, startCol, startIndex));
    }
  }
}
